--bind /home/branch/downloads /home/branch/downloads 
--bind /home/branch/videos /home/branch/mvideos
--bind /home/branch/pictures /home/branch/pictures
--bind /home/branch/music /home/branch/music
--bind /home/branch/documents /home/branch/documents
