# neru在收到hotkey时不会独占它,
# 所以改在niri.kdl中定义.
[hotkeys]
"Primary+Shift+C" = "__disabled__"
# "Cmd+Shift+C" = "recursive_grid"
"Primary+Shift+Space"= "__disabled__"
"Primary+Shift+G"= "__disabled__"
# "Cmd+Shift+G"= "grid"
"Primary+Shift+S" = "__disabled__"
# "Cmd+Shift+S" = "scroll"
